# Generated by Django 5.1.1 on 2024-09-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda')], default='kutilmoqda', max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ElonCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters_value', models.CharField(blank=True, max_length=255, null=True)),
                ('elon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.characterauto')),
            ],
        ),
        migrations.CreateModel(
            name='ElonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.eloncharacter')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.files')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('measure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.measure')),
            ],
        ),
        migrations.AddField(
            model_name='eloncharacter',
            name='parameters_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.parameters'),
        ),
        migrations.CreateModel(
            name='ParametersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.files')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.parameters')),
            ],
        ),
        migrations.AddField(
            model_name='eloncharacter',
            name='parameters_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.parametersitem'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.parameters')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.files')),
            ],
        ),
        migrations.AddField(
            model_name='characterauto',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avto.users'),
        ),
    ]
