name: Django CI/CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh-key
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd https://github.com/xurshiddev555/AvtoElonUz.git
          git pull
          systemctl restart django_null.service
          systemctl reload nginx.service
          
git add .
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/xurshiddev555/AvtoElonUz.git
git push -u origin main